version: "3.8"

services:

  nginx-port-1:
    image: nginx:latest
    container_name: nginx-port-1
    # Long Syntaxes
    ports:
      - protocol: tcp
        published: 8080
        target: 80
    deploy:
      resources:
        reservations:
          cpus: "0.25"
          memory: 50m
        limits:
          cpus: "0.50"
          memory: 100m