version: "3.8"

services:
  app:
    container_name: app
    build:
      context: "../app"
      dockerfile: ../app/Dockerfile
    image: "app-golang:1.0.2"
    environment:
      - "APP_PORT=8080"
      - "MODE=production"
    ports:
      - "8080:8080"